export class Now{
  public text:string= ""
  public code:string= ''
  public temperature:string=''
  public feels_like:string= ""
  public pressure: string=""
  public humidity:string= ""
  public visibility:string= ""
  public wind_direction:string= ""
  public wind_direction_degree:string= ""
  public wind_speed:string= ""
  public  wind_scale:string= ""
  public clouds:string= ""
  public dew_point:string=''
}